### ISSUE TITLE
error on catkin build

### ISSUE THREAD

**Issue by GYJamor** [ethz-asl/volumetric_mapping#86]
catkin_simple-extras.cmake:38 (find_package):
  By not providing "Findcatkin_boost_python_buildtool.cmake" in
  CMAKE_MODULE_PATH this project has asked CMake to find a package
  configuration file provided by "catkin_boost_python_buildtool", but CMake
  did not find one.

  Could not find a package configuration file provided by
  "catkin_boost_python_buildtool" with any of the following names:

    catkin_boost_python_buildtoolConfig.cmake
    catkin_boost_python_buildtool-config.cmake

  Add the installation prefix of "catkin_boost_python_buildtool" to
  CMAKE_PREFIX_PATH or set "catkin_boost_python_buildtool_DIR" to a directory
  containing one of the above files.  If "catkin_boost_python_buildtool"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:5 (catkin_simple)

Failed     << minkindr_python:cmake               [ Exited with code 1 ]       
Failed    <<< minkindr_python                     [ 0.5 seconds ]

**Comment by mzahana** [comment]
Facing same issue. @GYJamor did you find a solution?

**Comment by alexmillane** [comment]
The problem is that you're inadvertently trying to build minkindr_python which is in your workspace.

Either "catkin ignore" minkindr_python or install catkin_boost_python_buildtool as indicated by the error message (https://github.com/ethz-asl/catkin_boost_python_buildtool).
