### ISSUE TITLE
volumetric_map_base/lib/libvolumetric_map_base.so: undefined reference to `cv::Mat::updateContinuityFlag()'

### ISSUE THREAD

**Issue by youmi-zym** [ethz-asl/volumetric_mapping#89]
Hi, 
  I build your project on Ubuntu18.04, with ros version melodic and OpenCV3.4.3, but I still get above error, do you have some advice for it?

[ 60%] Linking CXX shared library /home/user/tools/planner/mbplanner_ws/devel_isolated/octomap_world/lib/liboctomap_world.so
[ 60%] Built target octomap_world
Scanning dependencies of target octomap_manager
[ 80%] Building CXX object CMakeFiles/octomap_manager.dir/src/octomap_manager_node.cc.o
[100%] Linking CXX executable /home/user/tools/planner/mbplanner_ws/devel_isolated/octomap_world/lib/octomap_world/octomap_manager
/home/user/tools/planner/mbplanner_ws/devel_isolated/volumetric_map_base/lib/libvolumetric_map_base.so: undefined reference to `cv::Mat::updateContinuityFlag()'
collect2: error: ld returned 1 exit status
CMakeFiles/octomap_manager.dir/build.make:633: recipe for target '/home/user/tools/planner/mbplanner_ws/devel_isolated/octomap_world/lib/octomap_world/octomap_manager' failed
make[2]: *** [/home/user/tools/planner/mbplanner_ws/devel_isolated/octomap_world/lib/octomap_world/octomap_manager] Error 1
CMakeFiles/Makefile2:1761: recipe for target 'CMakeFiles/octomap_manager.dir/all' failed
make[1]: *** [CMakeFiles/octomap_manager.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
<== Failed to process package 'octomap_world': 
  Command '['/home/user/tools/planner/mbplanner_ws/devel_isolated/volumetric_msgs/env.sh', 'make', '-j32']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /home/user/tools/planner/mbplanner_ws/build_isolated/octomap_world && /home/user/tools/planner/mbplanner_ws/devel_isolated/volumetric_msgs/env.sh make -j32

Command failed, exiting.

Thanks.

**Comment by greymaner** [comment]
@youmi-zym  hi, I have the same problem right now ,how did you solve this error?please~ :)
